export const SEC_IN_MILLISECONDS = 1000;

export const MIN_IN_MILLISECONDS = 60 * SEC_IN_MILLISECONDS;

export const HOUR_IN_MILLISECONDS = 60 * MIN_IN_MILLISECONDS;

export const DAY_IN_MILLISECONDS = 24 * HOUR_IN_MILLISECONDS;

export const WEEK_IN_MILLISECONDS = 7 * DAY_IN_MILLISECONDS;

export const MONTH_IN_MILLISECONDS = 30 * DAY_IN_MILLISECONDS;

